import { type NextPage } from "next";
import Head from "next/head";
import { ButtonLink } from "../components/ui/ButtonLink";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ButtonLink href="/measures/new">Dodaj nowy pomiar</ButtonLink>
      </main>
    </>
  );
};

export default Home;
