import { type NextPage } from "next";
import Head from "next/head";
import { ButtonLink } from "../components/ui/ButtonLink";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const { data } = api.measure.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Measure 💪</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ButtonLink href="/measures/new">Dodaj nowy pomiar</ButtonLink>
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
    </>
  );
};

export default Home;
